# Generated by Django 4.1 on 2022-10-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='team/images/')),
                ('name', models.CharField(max_length=255)),
                ('job_role', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'web_team',
                'ordering': ['id'],
            },
        ),
    ]
