# Generated by Django 4.1 on 2022-10-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='customer/images/')),
            ],
            options={
                'db_table': 'web_customers',
                'ordering': ['id'],
            },
        ),
    ]
