# Generated by Django 4.1 on 2022-10-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=128)),
                ('country', models.CharField(choices=[('1', 'STARTER'), ('2', 'MEDIUM'), ('2', 'COMPLETE')], max_length=128)),
                ('user_agreement', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'web_contact',
                'ordering': ['id'],
            },
        ),
    ]
