# Generated by Django 4.1 on 2022-10-22 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='country',
            new_name='interest',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='company',
            new_name='number',
        ),
    ]
